### GENERAL SETTINGS ###

# Site settings
title: "清华大学 TUNA 协会"
brand: "清华大学 TUNA 协会"
description: "前·清华大学网管会"
baseurl: "" #important: start with /
url: "https://tuna.moe"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
permalink: "/:categories/:year/:title/"
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

future: true
google_verify: Lwh0NyQ1YAKRuLlXXkk0_QvgJpGLRQVA8xaoRn81Ysk

vite:
    config_path: _src/vite.json
    viteConfig: _vite.config.mjs

plugins:
    - jekyll-minifier
    - jekyll/fontawesome/svg

babel_js_extensions: 'es6'
jekyll-minifier:
    exclude:
        - "cal.ics"
        - "assets/*"

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "清华大学 TUNA 协会原名清华大学学生网管会，注册名清华大学学生网络与开源软件协会，是由清华大学网络技术和开源软件爱好者、技术宅组成的团体。现阶段向校内外提供开源软件镜像等服务。"

include: ['_pages']

addition_exclude:
    - package.json
    - package-lock.json
    - node_modules/
    - Gemfile
    - Gemfile.lock
    - README.md
    - vendor/
    - Dockerfile*
    - LICENSE
