name: Jekyll Build & Deploy

on: [push, pull_request]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build the site in the tunathu/mirror-web container
        run: |
          echo "Working on ref ${{github.ref}}"
          docker run --user "$(id -u):$(id -g)" --env NODE_ENV=production --env HOME=/tmp -v ${{ github.workspace }}:/data tunathu/mirror-web:latest npm ci
          docker run --user "$(id -u):$(id -g)" --env JEKYLL_ENV=production --env VISUALIZER=true -v ${{ github.workspace }}:/data tunathu/mirror-web:latest bash -c "HOME=/tmp npm install rollup-plugin-visualizer && jekyll build --future"
      - name: Upload artifacts
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'
          name: 'gh-pages-${{github.sha}}'
      - name: Upload artifacts
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: actions/upload-artifact@v4
        with:
          path: '_site'
          name: gh-pages-${{github.sha}}
      - name: Upload size analysis
        uses: actions/upload-artifact@v4
        with:
          path: '_stats.html'
          name: size-stats-${{github.sha}}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_upload
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'gh-pages-${{github.sha}}'
